Document: pixelpulse2
Title: Debian pixelpulse2 Manual
Author: <insert document author here>
Abstract: This manual describes what pixelpulse2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pixelpulse2/pixelpulse2.sgml.gz

Format: postscript
Files: /usr/share/doc/pixelpulse2/pixelpulse2.ps.gz

Format: text
Files: /usr/share/doc/pixelpulse2/pixelpulse2.text.gz

Format: HTML
Index: /usr/share/doc/pixelpulse2/html/index.html
Files: /usr/share/doc/pixelpulse2/html/*.html
